Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, cwd+"/include"]

src  = Glob('*.c')
src += Glob('*.S')

group = DefineGroup('CPU', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
